# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  my_job:
    name: Run-npm-on-Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - name: Setup Conan
  # You may pin to the exact commit or the version.
  # uses: jwidauer/setup-conan@37b9cc7ed87bdd5a6f48221536689741496ab84d
      uses: jwidauer/setup-conan@v1
      with:
  # Conan version to use
       version: # optional, default is 
    # Git repository to use when installing the Conan configuration
      config-git-repository: # optional, default is
      - run: npm test

      - name: Install Dependencies
          run: pip install resemble
